### ISSUE TITLE
Tiny typo in ch. 37

### ISSUE THREAD

**Issue by dajare** [standardebooks/p-g-wodehouse_mike#1]
Ch. XXXVII:

`kept them by his aide.` --> `kept them by his side.`

- [epub source line]( https://github.com/standardebooks/p-g-wodehouse_mike/blob/10b96e90c510c5224caadce6ec38e7541faaacd7/src/epub/text/chapter-37.xhtml#L34)
- [page scan confirmation]( https://archive.org/details/mikepublicschool00wodeuoft/page/209/mode/1up)

**Comment by acabal** [comment]
Thanks, this should be fixed now!
